package model;

import java.util.List;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.sql.Date;

import structures.CoursePrimaryKey;
import structures.SessionLocation;


@DynamoDBTable(tableName = SessionDirectory.tableName)
public class Session {
	 
	private Date startTime;
	private Date endTime;
	private CoursePrimaryKey course;
	private List<String> members;
	private String desciption;
	private SessionLocation location;
	private String id;
	

	public Session() {
		startTime = null;
		endTime = null;
		course = null;
		members = null;
		desciption = null;
		location = null;
		id = null;
	}
	
	public Session(String id) {
		this();
		this.setId(id);
	}

	@DynamoDBAttribute(attributeName = SessionDirectory.startTimeAttributeName)
	public Date getStartTime() {return startTime;}
	public void setStartTime(Date startTime) {this.startTime = startTime;}
	
	@DynamoDBAttribute(attributeName = SessionDirectory.endTimeAttributeName)
	public Date getEndTime() {return endTime;}
	public void setEndTime(Date endTime) {this.endTime  = endTime;}

	@DynamoDBAttribute(attributeName = SessionDirectory.courseAttributeName)
	public String getCourseString() {
		return course.getDepartment() + " " + Integer.toString(course.getNumber());		//Format: "EC 100"
	}
	public void setCourseWithString(String course) {
		String dep = course.substring(0, CourseDirectory.departmentCodeSize);
		String num = course.substring(CourseDirectory.departmentCodeSize + 1, course.length());
		
		this.course =  new CoursePrimaryKey(dep, Integer.parseInt(num));
	}

	@DynamoDBAttribute(attributeName = SessionDirectory.membersAttributeName)
	public List<String> getMembers() {return members;}
	public void setMembers(List<String> members) {this.members = members;}

	@DynamoDBAttribute(attributeName = SessionDirectory.descriptionAttributeName)
	public String getDesciption() {return desciption;}
	public void setDesciption(String desciption) {this.desciption = desciption;}

	@DynamoDBAttribute(attributeName = SessionDirectory.locationAttributeName)
	public SessionLocation getLocation() {return location;}
	public void setLocation(SessionLocation location) {this.location = location;}

	@DynamoDBHashKey(attributeName = SessionDirectory.idAttributeName)
	@DynamoDBAutoGeneratedKey
	public String getId() {return id;}
	public void setId(String id) {this.id = id;}
	
	
	public CoursePrimaryKey getCourse() {
		return course;
	}
	public void setCourse(CoursePrimaryKey courseId) {
		this.course = courseId;
	}
	
	
	
	
}
