package model;

import java.util.List;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import structures.CoursePrimaryKey;

@DynamoDBTable(tableName = UserDirectory.tableName)
public class User {

	private String firstName;
	private String lastName;
	private String id;
	private String email;
	private List<CoursePrimaryKey> courses;
	private List<String> sessions;
	private boolean verified;
	
	
	public User() {
		firstName = null;
		lastName = null;
		id = null;
		email = null;
		courses = null;
		sessions = null;
		verified = false;
	}
	
	public User(String id) {
		this();
		this.id = id;
	}
	
	public User(String firstName, String lastName, String email) {
		this();
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}
	
	public User(String firstName, String lastName, String id, String email, List<CoursePrimaryKey> courses, List<String> sessions, boolean verified) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.courses = courses;
		this.email = email;
		this.id = id;
		this.sessions = sessions;
		this.verified = verified;
	}


	@DynamoDBAttribute(attributeName = UserDirectory.firstNameAttributeName)
	public String getFirstName() {return firstName;}
	public void setFirstName(String firstName) {this.firstName = firstName;}
	
	@DynamoDBAttribute(attributeName = UserDirectory.lastNameAttributeName)
	public String getLastName() {return lastName;}
	public void setLastName(String lastName) {this.lastName = lastName;}
	
	@DynamoDBHashKey(attributeName = UserDirectory.idAttributeName)
	@DynamoDBAutoGeneratedKey
	public String getId() {return id;}
	public void setId(String id) {this.id = id;}

	@DynamoDBAttribute(attributeName = UserDirectory.emailAttributeName)
	public String getEmail() {return email;}
	public void setEmail(String email) throws Exception {
		if (UserDirectory.isValidEmail(email)) {
			this.email = email;
		}
		else
			throw new Exception("Error: Trying to set email to a non-BU email.");
	}

	@DynamoDBAttribute(attributeName = UserDirectory.coursesAttributeName)
	public List<CoursePrimaryKey> getCourses() {return courses;}
	public void setCourses(List<CoursePrimaryKey> courses) {this.courses = courses;}

	@DynamoDBAttribute(attributeName = UserDirectory.sessionsAttributeName)
	public List<String> getSessions() {return sessions;}
	public void setSessions(List<String> sessions) {this.sessions = sessions;}

	@DynamoDBAttribute(attributeName = UserDirectory.verifiedAttributeName)
	public boolean isVerified() {return verified;}
	public void setVerified(boolean verified) {this.verified = verified;}
}
